# Generated by Django 4.2.6 on 2023-10-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=100)),
                ('Descripcion', models.TextField(max_length=150)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
