# Generated by Django 4.2.7 on 2023-11-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
