# Generated by Django 4.2.6 on 2023-10-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Nombre',
            new_name='Usuario',
        ),
    ]
